//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_LocalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об автосервисе.
        /// </summary>
        public static string AboutCarService {
            get {
                return ResourceManager.GetString("AboutCarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обслуживаемые марки автомобилей.
        /// </summary>
        public static string AcceptedMarksList {
            get {
                return ResourceManager.GetString("AcceptedMarksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить авто.
        /// </summary>
        public static string AddACar {
            get {
                return ResourceManager.GetString("AddACar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес автосервиса.
        /// </summary>
        public static string AddressCarService {
            get {
                return ResourceManager.GetString("AddressCarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка принята.
        /// </summary>
        public static string ApplicationAccepted {
            get {
                return ResourceManager.GetString("ApplicationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка отклонена.
        /// </summary>
        public static string ApplicationDeclined {
            get {
                return ResourceManager.GetString("ApplicationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки на регистрацию.
        /// </summary>
        public static string AppsForRegister {
            get {
                return ResourceManager.GetString("AppsForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка автосервиса.
        /// </summary>
        public static string AutoserviceCard {
            get {
                return ResourceManager.GetString("AutoserviceCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лучшие автосервисы.
        /// </summary>
        public static string BestServices {
            get {
                return ResourceManager.GetString("BestServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление автомобиля.
        /// </summary>
        public static string CarAdding {
            get {
                return ResourceManager.GetString("CarAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина успешно добавлена вам в гараж.
        /// </summary>
        public static string CarAddToGarageSuccess {
            get {
                return ResourceManager.GetString("CarAddToGarageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка автомобиля.
        /// </summary>
        public static string CarCard {
            get {
                return ResourceManager.GetString("CarCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объем двигателя:.
        /// </summary>
        public static string CarEngine {
            get {
                return ResourceManager.GetString("CarEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать объем двигателя автомобиля.
        /// </summary>
        public static string CarEngineRequired {
            get {
                return ResourceManager.GetString("CarEngineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип топлива:.
        /// </summary>
        public static string CarFuelType {
            get {
                return ResourceManager.GetString("CarFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать тип топлива автомобиля.
        /// </summary>
        public static string CarFuelTypeRequired {
            get {
                return ResourceManager.GetString("CarFuelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История работ.
        /// </summary>
        public static string CarHistory {
            get {
                return ResourceManager.GetString("CarHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка автомобиля:.
        /// </summary>
        public static string CarMark {
            get {
                return ResourceManager.GetString("CarMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель автомобиля:.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя авто (видно только Вам):.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать имя автомобиля.
        /// </summary>
        public static string CarNameIsRequired {
            get {
                return ResourceManager.GetString("CarNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосервис.
        /// </summary>
        public static string CarService {
            get {
                return ResourceManager.GetString("CarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать адрес автосервиса.
        /// </summary>
        public static string CarServiceAddressEmpty {
            get {
                return ResourceManager.GetString("CarServiceAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать email автосервиса.
        /// </summary>
        public static string CarServiceEmailIsEmpty {
            get {
                return ResourceManager.GetString("CarServiceEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логотип автосервиса.
        /// </summary>
        public static string CarServiceLogo {
            get {
                return ResourceManager.GetString("CarServiceLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование автосервиса.
        /// </summary>
        public static string CarServiceName {
            get {
                return ResourceManager.GetString("CarServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать название автосервиса.
        /// </summary>
        public static string CarServiceNameIsEmpty {
            get {
                return ResourceManager.GetString("CarServiceNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать мобильные номера автосервиса.
        /// </summary>
        public static string CarServicePhonesIsEmpty {
            get {
                return ResourceManager.GetString("CarServicePhonesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотографии автосервиса.
        /// </summary>
        public static string CarServicePhotos {
            get {
                return ResourceManager.GetString("CarServicePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация автосервиса.
        /// </summary>
        public static string CarServiceRegistration {
            get {
                return ResourceManager.GetString("CarServiceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт автосервиса.
        /// </summary>
        public static string CarServiceSite {
            get {
                return ResourceManager.GetString("CarServiceSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График работы автосервиса.
        /// </summary>
        public static string CarServiceWorkTime {
            get {
                return ResourceManager.GetString("CarServiceWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машины не найдены.
        /// </summary>
        public static string CarsNotFound {
            get {
                return ResourceManager.GetString("CarsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина успешно удалена.
        /// </summary>
        public static string CarSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("CarSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина успешно восстановлена.
        /// </summary>
        public static string CarSucessfullyRestored {
            get {
                return ResourceManager.GetString("CarSucessfullyRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год выпуска:.
        /// </summary>
        public static string CarYearOfAssembly {
            get {
                return ResourceManager.GetString("CarYearOfAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать год производства автомобиля.
        /// </summary>
        public static string CarYearRequired {
            get {
                return ResourceManager.GetString("CarYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите город.
        /// </summary>
        public static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать город автосервиса.
        /// </summary>
        public static string CityIsNotSelected {
            get {
                return ResourceManager.GetString("CityIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить форму.
        /// </summary>
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация клиента.
        /// </summary>
        public static string ClientRegistration {
            get {
                return ResourceManager.GetString("ClientRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакнтый e-mail автосервиса.
        /// </summary>
        public static string ContactEmailCarService {
            get {
                return ResourceManager.GetString("ContactEmailCarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактная информация.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить контакное имя.
        /// </summary>
        public static string ContactNameIsEmpty {
            get {
                return ResourceManager.GetString("ContactNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактный номер телефона.
        /// </summary>
        public static string ContactPhoneNumber {
            get {
                return ResourceManager.GetString("ContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактные номера телефонов.
        /// </summary>
        public static string ContactPhoneNumbers {
            get {
                return ResourceManager.GetString("ContactPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонить.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизель.
        /// </summary>
        public static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Илья Мжачев &amp; Федор Костюченко.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гараж.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бензин.
        /// </summary>
        public static string Gasoline {
            get {
                return ResourceManager.GetString("Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как это работает.
        /// </summary>
        public static string HomeHowItsWork {
            get {
                return ResourceManager.GetString("HomeHowItsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы представляем Вам площадку для взаимодействия автовладельцев с автосервисами Crimean-Mechanic.
        /// </summary>
        public static string HomeIntroducing {
            get {
                return ResourceManager.GetString("HomeIntroducing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подаете заявку на ремонт.
        /// </summary>
        public static string HomeStep1 {
            get {
                return ResourceManager.GetString("HomeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка попадает в систему.
        /// </summary>
        public static string HomeStep2 {
            get {
                return ResourceManager.GetString("HomeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосервисы отправляют предложения.
        /// </summary>
        public static string HomeStep3 {
            get {
                return ResourceManager.GetString("HomeStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбираете предолжение и принимаете его.
        /// </summary>
        public static string HomeStep4 {
            get {
                return ResourceManager.GetString("HomeStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string HomeStep5 {
            get {
                return ResourceManager.GetString("HomeStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Местоположение.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить логин пользователя.
        /// </summary>
        public static string LoginIsEmpty {
            get {
                return ResourceManager.GetString("LoginIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин должен быть e-mail адресом.
        /// </summary>
        public static string LoginIsNotEmail {
            get {
                return ResourceManager.GetString("LoginIsNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя менеджера.
        /// </summary>
        public static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать имя менеджера автосервиса.
        /// </summary>
        public static string ManagerNameIsEmpty {
            get {
                return ResourceManager.GetString("ManagerNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать модель автомобиля.
        /// </summary>
        public static string ModelSpecify {
            get {
                return ResourceManager.GetString("ModelSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мой гараж.
        /// </summary>
        public static string MyGarage {
            get {
                return ResourceManager.GetString("MyGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи не найдены.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другой.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить пароль.
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить телефонный номер.
        /// </summary>
        public static string PhoneNumberIsEmpty {
            get {
                return ResourceManager.GetString("PhoneNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотографии.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка заявки регистрации автосервиса.
        /// </summary>
        public static string RegApplicationCard {
            get {
                return ResourceManager.GetString("RegApplicationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Regisration {
            get {
                return ResourceManager.GetString("Regisration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистрации.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поля помеченные символом * - обязательны к заполнению.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на улица Ивановича 12.
        /// </summary>
        public static string SampleAddress {
            get {
                return ResourceManager.GetString("SampleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иванов Иван.
        /// </summary>
        public static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных автосервиса.
        /// </summary>
        public static string ServiceInformationEdit {
            get {
                return ResourceManager.GetString("ServiceInformationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка регистрации.
        /// </summary>
        public static string ServiceRegister {
            get {
                return ResourceManager.GetString("ServiceRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать удаленные.
        /// </summary>
        public static string ShowDeleted {
            get {
                return ResourceManager.GetString("ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка на регистрацию автосервиса успешно подана.
        /// </summary>
        public static string SuccessCarServiceRegistration {
            get {
                return ResourceManager.GetString("SuccessCarServiceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно прошел регистрацию.
        /// </summary>
        public static string SuccessUserRegistration {
            get {
                return ResourceManager.GetString("SuccessUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин пользователя.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIN:.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vin-номер должен содержать 17 символов.
        /// </summary>
        public static string VinCharacters {
            get {
                return ResourceManager.GetString("VinCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать vin-номер автомобиля.
        /// </summary>
        public static string VinSpecify {
            get {
                return ResourceManager.GetString("VinSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень работ.
        /// </summary>
        public static string WorkTags {
            get {
                return ResourceManager.GetString("WorkTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение года.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
