//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogic.Resources.ValidationErrorResources", typeof(ValidationErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка автомобиля с номером {0} не найдена.
        /// </summary>
        public static string CarMarkNotFound {
            get {
                return ResourceManager.GetString("CarMarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель машины не найдена.
        /// </summary>
        public static string CarModelNotFound {
            get {
                return ResourceManager.GetString("CarModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес автосервиса не заполнен.
        /// </summary>
        public static string CarServiceAddressIsEmpty {
            get {
                return ResourceManager.GetString("CarServiceAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный контактный email адрес.
        /// </summary>
        public static string CarServiceContactEmailIsInvalid {
            get {
                return ResourceManager.GetString("CarServiceContactEmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактное имя менеджера автосервиса не заполнено.
        /// </summary>
        public static string CarServiceManagerNameIsEmpty {
            get {
                return ResourceManager.GetString("CarServiceManagerNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименнование автосервиса не заполнено.
        /// </summary>
        public static string CarServiceNameIsEmpty {
            get {
                return ResourceManager.GetString("CarServiceNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер {0} имеет неправильный формат.
        /// </summary>
        public static string CarServicePhoneIsIncorrect {
            get {
                return ResourceManager.GetString("CarServicePhoneIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать хотя бы один контактный мобильный номер.
        /// </summary>
        public static string CarServicePhonesIsEmpty {
            get {
                return ResourceManager.GetString("CarServicePhonesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неккоректный адрес сайта автосервиса.
        /// </summary>
        public static string CarServiceSiteIsIncorrect {
            get {
                return ResourceManager.GetString("CarServiceSiteIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город не найден.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутсвует контактное имя пользователя.
        /// </summary>
        public static string ContactNameIsEmpty {
            get {
                return ResourceManager.GetString("ContactNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не был указан тип топливной системы автомобиля.
        /// </summary>
        public static string FuelTypeNotFound {
            get {
                return ResourceManager.GetString("FuelTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &quot;{0}&quot; содержит недопустимое расширение.
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин пользователя.
        /// </summary>
        public static string LoginIsNotValid {
            get {
                return ResourceManager.GetString("LoginIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный номер мобильного телефона.
        /// </summary>
        public static string PhoneNumberIsIncorrect {
            get {
                return ResourceManager.GetString("PhoneNumberIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машина пользователя не найдена.
        /// </summary>
        public static string UserCarNotFound {
            get {
                return ResourceManager.GetString("UserCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный VIN номер автомобиля.
        /// </summary>
        public static string VinNumberIsIncorrect {
            get {
                return ResourceManager.GetString("VinNumberIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид работы с номером {0} не найден.
        /// </summary>
        public static string WorkTagNotFound {
            get {
                return ResourceManager.GetString("WorkTagNotFound", resourceCulture);
            }
        }
    }
}
